language: php

sudo: true

cache:
  directories:
    - $HOME/.composer/cache

addons:
  apt:
    packages:
    - chromium-chromedriver
    - gdebi-core

env:
  global:
    - MOODLE_START_BEHAT_SERVERS=NO
    - DB=mysqli
    - MOODLE_CI_VER=1

matrix:
 include:
  #- php: 5.4
  #  env: MOODLE_BRANCH=MOODLE_29_STABLE AWS_BRANCH=LEGACY TOPCOLL_BRANCH=MOODLE_29
  #- php: 5.4
  #  env: MOODLE_BRANCH=MOODLE_30_STABLE AWS_BRANCH=LEGACY TOPCOLL_BRANCH=MOODLE_30
  #- php: 5.4
  #  env: MOODLE_BRANCH=MOODLE_31_STABLE AWS_BRANCH=LEGACY TOPCOLL_BRANCH=MOODLE_31
  #- php: 5.5
  #  env: MOODLE_BRANCH=MOODLE_29_STABLE AWS_BRANCH=LEGACY TOPCOLL_BRANCH=MOODLE_29
  #- php: 5.5
  #  env: MOODLE_BRANCH=MOODLE_30_STABLE AWS_BRANCH=LEGACY TOPCOLL_BRANCH=MOODLE_30
  #- php: 5.5
  #  env: MOODLE_BRANCH=MOODLE_31_STABLE AWS_BRANCH=MOODLE_31_STABLE TOPCOLL_BRANCH=MOODLE_31
  #- php: 5.6
  #  env: MOODLE_BRANCH=MOODLE_29_STABLE AWS_BRANCH=LEGACY TOPCOLL_BRANCH=MOODLE_29
  #- php: 5.6
  #  env: MOODLE_BRANCH=MOODLE_30_STABLE AWS_BRANCH=LEGACY TOPCOLL_BRANCH=MOODLE_30
  #- php: 5.6
  #  env: MOODLE_BRANCH=MOODLE_31_STABLE AWS_BRANCH=MOODLE_31_STABLE TOPCOLL_BRANCH=MOODLE_31
  #- php: 5.6
  #  env: MOODLE_BRANCH=MOODLE_32_STABLE AWS_BRANCH=MOODLE_32_STABLE TOPCOLL_BRANCH=MOODLE_32 MOODLE_CI_VER=2
  #- php: 7.0
  #  env: MOODLE_BRANCH=MOODLE_30_STABLE AWS_BRANCH=LEGACY TOPCOLL_BRANCH=MOODLE_30
  #- php: 7.0
  #  env: MOODLE_BRANCH=MOODLE_31_STABLE AWS_BRANCH=MOODLE_31_STABLE TOPCOLL_BRANCH=MOODLE_31
  - php: 7.0
    env: MOODLE_BRANCH=MOODLE_32_STABLE AWS_BRANCH=MOODLE_32_STABLE TOPCOLL_BRANCH=MOODLE_32 MOODLE_CI_VER=2
  #- php: 7.1
  #  env: MOODLE_BRANCH=MOODLE_32_STABLE AWS_BRANCH=MOODLE_32_STABLE TOPCOLL_BRANCH=MOODLE_32 MOODLE_CI_VER=2


before_install:
  #- curl -L -s -o /tmp/ff.deb https://sourceforge.net/projects/ubuntuzilla/files/mozilla/apt/pool/main/f/firefox-mozilla-build/firefox-mozilla-build_40.0.3-0ubuntu1_amd64.deb/download
  #- sudo gdebi -q -n /tmp/ff.deb
  - sudo apt-get purge firefox
  - sudo apt-get install -y -q firefox=28.0+build2-0ubuntu2
  - sudo updatedb
  - locate firefox
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^${MOODLE_CI_VER}
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"
  - sleep 10

# See
# https://seleniumhq.github.io/selenium/docs/api/java/constant-values.html#org.openqa.selenium.firefox.FirefoxOptions.FIREFOX_OPTIONS
# For specific firefox settings with regards to override
# -Dwebdriver.firefox.bin=/opt/firefox/firefox

install:
  - moodle-plugin-ci add-plugin -b ${AWS_BRANCH}     moodlerooms/moodle-local_aws_sdk
  - moodle-plugin-ci add-plugin -b ${MOODLE_BRANCH}  moodlerooms/moodle-local_mr
  - moodle-plugin-ci add-plugin -b ${MOODLE_BRANCH}  moodlerooms/moodle-mod_hsuforum
  - moodle-plugin-ci add-plugin -b ${MOODLE_BRANCH}  moodlerooms/moodle-theme_snap
  #- moodle-plugin-ci add-plugin -b ${MOODLE_BRANCH}  moodlerooms/moodle-block_flexpagenav
  #- moodle-plugin-ci add-plugin -b ${MOODLE_BRANCH}  moodlerooms/moodle-block_flexpagemod
  #- moodle-plugin-ci add-plugin -b ${MOODLE_BRANCH}  moodlerooms/moodle-format_flexpage
  #- moodle-plugin-ci add-plugin -b ${MOODLE_BRANCH}  moodlerooms/moodle-theme_flexpage
  - moodle-plugin-ci add-plugin -b ${TOPCOLL_BRANCH} gjb2048/moodle-format_topcoll
  - moodle-plugin-ci install
  #- moodle-plugin-ci add-config '$CFG->behat_profiles=["default" => ["browser" => "chrome", "wd_host" => "http://localhost:4444/wd/hub", "extensions" => ["Behat\MinkExtension" => ["selenium2" => ["browser" => "chrome"]]]]];'
  #- cd /home/travis/build/moodle/
  #- php admin/tool/behat/cli/util.php --enable
  - xvfb-run -a --server-args="-screen 0 1024x768x24" java -jar /home/travis/build/moodle/selenium.jar -port 4444 -Dwebdriver.chrome.driver=/usr/lib/chromium-browser/chromedriver -Dwebdriver.firefox.bin=/usr/bin/firefox > /tmp/access.log 2> /tmp/error.log &
  - php -t /home/travis/build/moodle/ -S localhost:8000 > /tmp/php-access.log 2> /tmp/php-error.log &
  - sleep 80

script:
  #- moodle-plugin-ci phplint
  #- moodle-plugin-ci codechecker
  #- moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
