language: php

sudo: true

cache:
  directories:
    - $HOME/.composer/cache

php:
 - 5.4

env:
  global:
    - AWS_BRANCH=LEGACY
    - DB=mysqli
    - MOODLE_START_BEHAT_SERVERS=NO
  matrix:
    - MOODLE_BRANCH=MOODLE_29_STABLE
    - MOODLE_BRANCH=MOODLE_30_STABLE
    - MOODLE_BRANCH=MOODLE_31_STABLE

addons:
  apt:
    packages:
    - chromium-chromedriver
    - gdebi-core

#java-1.7.0-openjdk-amd64 1071 /usr/lib/jvm/java-1.7.0-openjdk-amd64
#java-1.8.0-openjdk-amd64 1069 /usr/lib/jvm/java-1.8.0-openjdk-amd64
#java-8-oracle 1081 /usr/lib/jvm/java-8-oracle
#java-9-oracle 1091 /usr/lib/jvm/java-9-oracle

#matrix:
# include:
#  - php: 5.4
#    env: MOODLE_BRANCH=MOODLE_29_STABLE AWS_BRANCH=LEGACY DB=mysqli
#  - php: 5.4
#    env: MOODLE_BRANCH=MOODLE_30_STABLE AWS_BRANCH=LEGACY DB=mysqli
#  - php: 5.4
#    env: MOODLE_BRANCH=MOODLE_31_STABLE AWS_BRANCH=LEGACY DB=mysqli
#

before_install:
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^1
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"
  #- jdk_switcher use oraclejdk8
  # Trying to adress the intermittent faliure of MySQL server
  # See https://github.com/travis-ci/travis-ci/issues/6842 for details
  - sleep 10

install:
  #- sudo apt-get -y -q update
  #- sudo apt-get -y -q purge firefox
  #- curl -L -o /tmp/ff.deb https://downloads.sourceforge.net/project/ubuntuzilla/mozilla/apt/pool/main/f/firefox-mozilla-build/firefox-mozilla-build_40.0.3-0ubuntu1_amd64.deb
  #- sudo gdebi -q -n /tmp/ff.deb
  - moodle-plugin-ci add-plugin -b ${AWS_BRANCH}    moodlerooms/moodle-local_aws_sdk
  - moodle-plugin-ci add-plugin -b ${MOODLE_BRANCH} moodlerooms/moodle-local_mr
  - moodle-plugin-ci add-plugin -b ${MOODLE_BRANCH} moodlerooms/moodle-mod_hsuforum
  - moodle-plugin-ci -vvv install
  - moodle-plugin-ci add-config '$CFG->behat_profiles=["default" => ["browser" => "chrome", "wd_host" => "http://localhost:4444/wd/hub", "extensions" => ["Behat\MinkExtension" => ["selenium2" => ["browser" => "chrome"]]]]];'
  - xvfb-run -a --server-args="-screen 0 1024x768x24" java -jar /home/travis/build/moodle/selenium.jar -port 4444 &
  - cd /home/travis/build/moodle/
  - php -t /home/travis/build/moodle/ -S localhost:8000 &
  - sleep 80

script:
  - moodle-plugin-ci phplint
#  - moodle-plugin-ci phpcpd
#  - moodle-plugin-ci phpmd
#  - moodle-plugin-ci codechecker
#  - moodle-plugin-ci csslint
#  - moodle-plugin-ci shifter
#  - moodle-plugin-ci jshint
#  - moodle-plugin-ci validate
#  - moodle-plugin-ci phpunit
  - moodle-plugin-ci -vvv behat
