dist: precise

sudo: true

language: php

cache:
  directories:
    - $HOME/.composer/cache

services:
  - mysql

env:
  global:
    - DB=mysqli
    - MOODLE_CI_VER=1

matrix:
 include:
  - php: 5.4
    env: MOODLE_BRANCH=MOODLE_29_STABLE AWS_BRANCH=LEGACY TOPCOLL_BRANCH=MOODLE_29
  - php: 5.4
    env: MOODLE_BRANCH=MOODLE_30_STABLE AWS_BRANCH=LEGACY TOPCOLL_BRANCH=MOODLE_30
  - php: 5.4
    env: MOODLE_BRANCH=MOODLE_31_STABLE AWS_BRANCH=LEGACY TOPCOLL_BRANCH=MOODLE_31
  - php: 5.5
    env: MOODLE_BRANCH=MOODLE_29_STABLE AWS_BRANCH=LEGACY TOPCOLL_BRANCH=MOODLE_29
  - php: 5.5
    env: MOODLE_BRANCH=MOODLE_30_STABLE AWS_BRANCH=LEGACY TOPCOLL_BRANCH=MOODLE_30
  - php: 5.5
    env: MOODLE_BRANCH=MOODLE_31_STABLE AWS_BRANCH=MOODLE_31_STABLE TOPCOLL_BRANCH=MOODLE_31
  - php: 5.6
    env: MOODLE_BRANCH=MOODLE_29_STABLE AWS_BRANCH=LEGACY TOPCOLL_BRANCH=MOODLE_29
  - php: 5.6
    env: MOODLE_BRANCH=MOODLE_30_STABLE AWS_BRANCH=LEGACY TOPCOLL_BRANCH=MOODLE_30
  - php: 5.6
    env: MOODLE_BRANCH=MOODLE_31_STABLE AWS_BRANCH=MOODLE_31_STABLE TOPCOLL_BRANCH=MOODLE_31
  - php: 5.6
    env: MOODLE_BRANCH=MOODLE_32_STABLE AWS_BRANCH=MOODLE_32_STABLE TOPCOLL_BRANCH=MOODLE_32
  - php: 7.0
    env: MOODLE_BRANCH=MOODLE_30_STABLE AWS_BRANCH=LEGACY TOPCOLL_BRANCH=MOODLE_30
  - php: 7.0
    env: MOODLE_BRANCH=MOODLE_31_STABLE AWS_BRANCH=MOODLE_31_STABLE TOPCOLL_BRANCH=MOODLE_31
  - php: 7.0
    env: MOODLE_BRANCH=MOODLE_32_STABLE AWS_BRANCH=MOODLE_32_STABLE TOPCOLL_BRANCH=MOODLE_32
  - php: 7.1
    env: MOODLE_BRANCH=MOODLE_32_STABLE AWS_BRANCH=MOODLE_32_STABLE TOPCOLL_BRANCH=MOODLE_32

before_install:
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^${MOODLE_CI_VER}
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci add-plugin -b ${AWS_BRANCH}     moodlerooms/moodle-local_aws_sdk
  - moodle-plugin-ci add-plugin -b ${MOODLE_BRANCH}  moodlerooms/moodle-local_mr
  - moodle-plugin-ci add-plugin -b ${MOODLE_BRANCH}  moodlerooms/moodle-mod_hsuforum
  - moodle-plugin-ci install

# We do not include behat testing for now since there are numerous issues
# with the tests them selves that need to be resolved before doing that.
script:
  - moodle-plugin-ci validate
  - moodle-plugin-ci phplint
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci phpunit
