language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
 - 5.4

env:
  global:
    - AWS_BRANCH=LEGACY
    - DB=mysqli
    - MOODLE_START_BEHAT_SERVERS=NO
  matrix:
    - MOODLE_BRANCH=MOODLE_29_STABLE
    - MOODLE_BRANCH=MOODLE_30_STABLE
    - MOODLE_BRANCH=MOODLE_31_STABLE

#addons:
#  apt:
#    packages:
#    - oracle-java8-installer
#java-1.7.0-openjdk-amd64 1071 /usr/lib/jvm/java-1.7.0-openjdk-amd64
#java-1.8.0-openjdk-amd64 1069 /usr/lib/jvm/java-1.8.0-openjdk-amd64
#java-8-oracle 1081 /usr/lib/jvm/java-8-oracle
#java-9-oracle 1091 /usr/lib/jvm/java-9-oracle

#matrix:
# include:
#  - php: 5.4
#    env: MOODLE_BRANCH=MOODLE_29_STABLE AWS_BRANCH=LEGACY DB=mysqli
#  - php: 5.4
#    env: MOODLE_BRANCH=MOODLE_30_STABLE AWS_BRANCH=LEGACY DB=mysqli
#  - php: 5.4
#    env: MOODLE_BRANCH=MOODLE_31_STABLE AWS_BRANCH=LEGACY DB=mysqli
#
#

before_install:
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^1
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"
  - jdk_switcher use oraclejdk8
  # Trying to adress the intermittent faliure of MySQL server
  # See https://github.com/travis-ci/travis-ci/issues/6842 for details
  - sleep 5

install:
  - moodle-plugin-ci add-plugin -b ${AWS_BRANCH} moodlerooms/moodle-local_aws_sdk
  - moodle-plugin-ci add-plugin -b ${MOODLE_BRANCH} moodlerooms/moodle-local_mr
  - moodle-plugin-ci add-plugin -b ${MOODLE_BRANCH} moodlerooms/moodle-mod_hsuforum
  - moodle-plugin-ci -vvv install
  - xvfb-run -a --server-args="-screen 0 1024x768x24" java -verbose -jar /home/travis/build/moodle/selenium.jar  > /home/travis/build/moodle/selenium.log &
  - cat /home/travis/build/moodle/selenium.log
  - php -S localhost:8000 &
  - curl -v http://localhost:4444/wd/hub/status
  - curl -v http://localhost:8000

script:
  - moodle-plugin-ci phplint
#  - moodle-plugin-ci phpcpd
#  - moodle-plugin-ci phpmd
#  - moodle-plugin-ci codechecker
#  - moodle-plugin-ci csslint
#  - moodle-plugin-ci shifter
#  - moodle-plugin-ci jshint
#  - moodle-plugin-ci validate
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci -vvv behat

