dist: trusty
sudo: false

addons:
  firefox: "47.0.1"
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java8-set-default
      - chromium-chromedriver

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

services:
  - mysql

env:
  global:
    - DB=mysqli
    - MOODLE_CI_VER=2
    - AWS_BRANCH=LEGACY
    - IGNORE_PATHS=amd/src/toggle_categories.js

matrix:
 include:
  - php: 5.4
    env: MOODLE_BRANCH=MOODLE_29_STABLE MOODLE_CI_VER=1
  - php: 5.4
    env: MOODLE_BRANCH=MOODLE_30_STABLE MOODLE_CI_VER=1
  - php: 5.4
    env: MOODLE_BRANCH=MOODLE_31_STABLE MOODLE_CI_VER=1
  - php: 5.5
    env: MOODLE_BRANCH=MOODLE_29_STABLE MOODLE_CI_VER=1
  - php: 5.5
    env: MOODLE_BRANCH=MOODLE_30_STABLE MOODLE_CI_VER=1
  - php: 5.5
    env: MOODLE_BRANCH=MOODLE_31_STABLE AWS_BRANCH=MOODLE_31_STABLE MOODLE_CI_VER=1
  - php: 5.6
    env: MOODLE_BRANCH=MOODLE_29_STABLE MOODLE_CI_VER=1
  - php: 5.6
    env: MOODLE_BRANCH=MOODLE_30_STABLE MOODLE_CI_VER=1
  - php: 5.6
    env: MOODLE_BRANCH=MOODLE_31_STABLE AWS_BRANCH=MOODLE_31_STABLE MOODLE_CI_VER=1
  - php: 5.6
    env: MOODLE_BRANCH=MOODLE_32_STABLE AWS_BRANCH=MOODLE_32_STABLE
  - php: 5.6
    env: MOODLE_BRANCH=MOODLE_33_STABLE AWS_BRANCH=MOODLE_33_STABLE
  - php: 7.0
    env: MOODLE_BRANCH=MOODLE_30_STABLE MOODLE_CI_VER=1
  - php: 7.0
    env: MOODLE_BRANCH=MOODLE_31_STABLE AWS_BRANCH=MOODLE_31_STABLE MOODLE_CI_VER=1
  - php: 7.0
    env: MOODLE_BRANCH=MOODLE_32_STABLE AWS_BRANCH=MOODLE_32_STABLE
  - php: 7.0
    env: MOODLE_BRANCH=MOODLE_33_STABLE AWS_BRANCH=MOODLE_33_STABLE
  - php: 7.1
    env: MOODLE_BRANCH=MOODLE_32_STABLE AWS_BRANCH=MOODLE_32_STABLE
  - php: 7.1
    env: MOODLE_BRANCH=MOODLE_33_STABLE AWS_BRANCH=MOODLE_33_STABLE

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 8.9
  - nvm use 8.9
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^${MOODLE_CI_VER}
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci add-plugin -b ${AWS_BRANCH}    moodlerooms/moodle-local_aws_sdk
  - moodle-plugin-ci add-plugin -b ${MOODLE_BRANCH} moodlerooms/moodle-local_mr
  - moodle-plugin-ci add-plugin -b ${MOODLE_BRANCH} moodlerooms/moodle-mod_hsuforum
  - moodle-plugin-ci install

# We do not include behat testing for now since there are numerous issues
# with the tests themselves that need to be resolved before doing that.
script:
  - moodle-plugin-ci validate
  - moodle-plugin-ci phplint
  - moodle-plugin-ci codechecker
  - if [ ${MOODLE_CI_VER} -eq 2 ] ; then moodle-plugin-ci savepoints ; fi
  - moodle-plugin-ci phpunit
